os: linux
language: node_js
jobs:
  include:
  - language: node_js
    node_js:
    - 10
    before_script:
    - cd Back/
    script:
    - npm install
    - npm test
notifications:
  email: false
env:
  global:
    secure: YqxeEsxkKzikfee7gcmYxfhK8at5akd+BeVxXKlxBjmmBLPRJ5TEYpabsi3Todai0m7XkS0KTQY1bDVv5zcwY6vZqg205KVIClTOa2cNq0+rMWevezgTF7rSCUaSykX2S0w39F8RD2RDAab/x8UWJANnD7CQ6yE4KtGzjkUKZK08VCR2AHC09NXP9N3Yw80FeZo94CDFT1eVHiW+oJhtMAae3lxXM3BXvtgwnKJTTwy+8gWGJ2zKHwuhgq0WqB/5cFVOSUtysHgCS5SUJaJ75yBjQmAjydgitnVffOwYTTac3uLNObfMozHfZrsdHFYZvMRTUwAZiwemYiKP02VnenyiiZ+t88m1vv+EAYQKhi6VKTXy0PddxA72FqscjUyJueKWEqOUG1jsMjwofGED7c0blRNbEoErXm2v2+BfKCBenZo+u/m1OgY5LnlrFAvuYU6bRLl4/1sutM+4JeN46HuD3IdNoAtgenoe+gY8rp9tKTelu258kSRwKCJOnxY8wS/lFuLcotUVsfQU2xyHraoVdAgy5E1Bd9fJC4BOu3n9D+iIOkqKmbjMyPiMn9X3hq6U9642IlGj0h9L9x/XP9K75yPArReL0t0GKXQRNQ63B2Ag0ut/LCXWvEfnkWiVIVgBUJp4Z1/CththtRMNPxKeHnKe19EhL6cEN8MinJA=
