os: linux
language: node_js
jobs:
  include:
  - language: node_js
    node_js:
    - 10
    before_script:
    - cd Back/
    - ls -al
    - 
    script:
    - npm install
    - npm test
notifications:
  email: false
