name: nowaste
description: nowaste project
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^2.1.0
  cupertino_icons: ^0.1.0
  flutter_map: ^0.9.0
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  url_launcher: ^5.4.7
  dio: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env