name: districtaid
description: District Aid project
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^6.0.3
  cupertino_icons: ^1.0.0
  dio: ">=3.0.10 <6.0.0"
  flutter_bloc: ^6.0.6
  flutter_dotenv: ^2.1.0
  flutter_map: ^0.10.1+1
  url_launcher: 5.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/splashscreen_1920px.png
    - assets/logo_small.png
