env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
name: Test, Build and Release apk
on:
  pull_request:
  push:
    branches:
      - master
    tags-ignore:
      - 'v0.*'
jobs:

  test:
    runs-on: ubuntu-latest
    name: Build and run tests
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.7.8+hotfix.4'

    - name: Flutter__Pub__Get
      working-directory: ./Front
      run: flutter pub get

    - name: Flutter__Upgrade
      working-directory: ./Front
      run: flutter upgrade

    - name: Flutter__Test
      working-directory: ./Front
      run: flutter test

    - name: Flutter__Build
      working-directory: ./Front
      run: flutter build apk --split-per-abi


  delivery:  
    name: Delivery APKs on Github package
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: nowaste-0.${{ steps.buildnumber.outputs.build_number }}
        draft: true
        prerelease: false

    - name: Upload release asset armeabi
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Front/build/app/outputs/apk/release/app-armeabi-v7a-release.apk
        asset_name: nowaste-${{ steps.buildnumber.outputs.build_number }}-armeabi-v7a.apk
        asset_content_type: application/vnd.android.package-archive

    - name: Upload release asset arm64-v8a
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Front/build/app/outputs/apk/release/app-arm64-v8a-release.apk
        asset_name: nowaste-${{ steps.buildnumber.outputs.build_number }}-arm64-v8a.apk
        asset_content_type: application/vnd.android.package-archive

    - name: Upload release asset x86_64
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Front/build/app/outputs/apk/release/app-x86_64-release.apk
        asset_name: nowaste-${{ steps.buildnumber.outputs.build_number }}-x86_64.apk
        asset_content_type: application/vnd.android.package-archive
