name: Node.js CI

env:
  TOKEN_OLD_TEST: ${{ secrets.TOKEN_OLD_TEST }}
  JWTSECRETKEY: ${{ secrets.JWTSECRETKEY }}
  NODE_ENV: test
  DB_HOST: localhost
  DB_USER: rootTester
  DB_PASSWORD: rootInThePlace
  DB_NAME: test
  CI: true

on:
  pull_request:
    branches:
      - master
      - 'Back*'
      - 'Front*'  
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.17.0]

    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_USER: developer
          MYSQL_PASSWORD: rootPowa
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:

      - uses: actions/checkout@v2

      # - name: Generate build number
      #   id: buildnumber
      #   uses: einaregilsson/build-number@v2 
      #   with:
      #     prefix: nowaste
      #     token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Shutdown Ubuntu MySQL (SUDO)
      #   run: sudo service mysql stop

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Use MariaDB
      #   uses: getong/mariadb-action@v1.1
      #   with:
      #     host port: 3800
      #     container port: 3307 
      #     character set server: 'utf8'
      #     collation server: 'utf8_general_ci'
      #     mariadb version: '10.4.10'
      #     mysql user: 'developer' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
      #     mysql password: 'rootPowa' # Required 


      # - name: Shutdown Ubuntu MySQL (SUDO)
      #   run: sudo service mysql start

      # - name: Verify MariaDB connection
      #   env:
      #     PORT: ${{ job.services.mariadb.ports[3309] }}
      #   run: |
      #     while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
      #       sleep 1
      #     done

      - name: Setup MariaDB data
        working-directory: ./Back
        run: netstat -tulpn
      
      - name: Setup MariaDB data
        working-directory: ./Back
        run: mysql -h"127.0.0.1" -P"3306" -u root -ppassword < './models/database/exportDB.sql'

      - name: Install Node.js Application 
        working-directory: ./Back
        run: npm install

      - name: Build Node.js Application 
        working-directory: ./Back
        run: npm run build --if-present

      - name: Test Node.js Application 
        working-directory: ./Back
        run: npm test