name: Node.js CI

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  pull_request:
    branches-ignore:
      - master
  push:
    branches:
      - master
    
jobs:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      node-version: [8.x, 10.x, 12.x]:

  test:
    steps:
      - uses: actions/checkout@v2
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v2 
        with:
          prefix: nowaste
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Test Node.js Application 
        env:
          CI: true
        run: 
          - npm install
          - npm run build --if-present
          - npm test
        
