name: Node.js CI

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MONGO_KEY: ${{ secrets.MONGO_KEY }}
  TOKEN_TEST: ${{ secrets.TOKEN_TEST }}
  JWTSECRETKEY: ${{ secrets.JWTSECRETKEY }}
  NODE_ENV: 'test'
  CI: true

on:
  pull_request:
    branches:
      - master
      - 'Back/*'
      - 'Front/*'  
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.17.0]

    steps:
      - uses: actions/checkout@v2

      # - name: Generate build number
      #   id: buildnumber
      #   uses: einaregilsson/build-number@v2 
      #   with:
      #     prefix: nowaste
      #     token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node.js Application 
        working-directory: ./Back
        run: npm install

      - name: Build Node.js Application 
        working-directory: ./Back
        run: npm run build --if-present

      - name: Test Node.js Application 
        working-directory: ./Back
        run: npm test
